# ==== Parkour Config ==== #
DefaultBlocks:
  Enabled: true
  Death:
    Material: STATIONARY_WATER
  Finish:
    Material: HUGE_MUSHROOM_2
  Climb:
    Material: BRICK
    Strength: 0.4
  Launch:
    Material: EMERALD_BLOCK
    Strength: 1.2
  Bounce:
    Material: MOSSY_COBBLESTONE
    Strength: 0.6
  Speed:
    Material: OBSIDIAN
    Strength: 5
    Duration: 200
  Repulse:
    Material: ENDER_STONE
    Strength: 0.4
  NoRun:
    Material: GOLD_BLOCK
  NoPotion:
    Material: HUGE_MUSHROOM_2
OnJoin:
  SetGamemode: 0
  DisplayFly: true
  EnforceWorld: true
  EnforceFinished: true
  AllowViaCommand: true
  Item:
    Suicide:
      Material: POISONOUS_POTATO
    HideAll:
      Material: BONE
    Leave:
      Material: SAPLING
OnCourse:
  EnforceParkourCommands:
    Enabled: true
    Whitelist:
    - login
  EnforceParkourSigns: true
  DisablePlayerDamage: false
  MaxFallTicks: 80
  AllowTrails: true
  DisableItemDrop: false
  LiveLeaderboard:
    Enabled: true
    Type: 1
OnFinish:
  EnforceCompletion: true
  TeleportToLobby: true
  SetGamemode: 0
  BroadcastLevel: 3
  DefaultPrize:
    Enabled: true
    Material: DIAMOND
    Amount: 1
    XP: 0
OnDie:
  SetXPBarToDeathCount: false
  ResetTimeWithNoCheckpoint: false
OnLeaveServer:
  LeaveCourse: false
  TeleportToLastCheckpoint: true
ParkourModes:
  CodJumper:
    Enabled: false
    ConfirmSet: true
  Spectate:
    OnStart:
      NotifyPlayer: true
    OnStop:
      RemainInvisible: false
      TeleportToLobby: true
Other:
  Economy:
    Enabled: true
  TitleActionBar:
    Enabled: true
  CheckForUpdates: true
  SubmitMetrics: true
  LogToFile: true
  DebugMode: false
  SignPermissions: false
  Parkour:
    ChatRankPrefix: false
    SignProtection: true
    InventoryManagement: true
    CommandPermissions: false
  Display:
    JoinWelcomeMessage: false
    CreatorJoin: true
    CourseNotFinished: true
    LevelReward: true
    TitleOnJoin: true
MySQL:
  Use: false
  Host: Host
  Port: 3306
  User: Username
  Password: Password
  Database: Database
  Table: Table
Version: 4.0
Lobby:
  Set: true
  World: gameworld
  X: 101.61992992795248
  Y: 6.0
  Z: 415.7551545020759
  Pitch: -9.300077
  Yaw: 180.23132
OnLeave:
  ResetPlayer: false
